server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul #security DB 접속정보
    username: user02
    password: user02
    
  mvc:
    view:
      prefix: #/templates/ pom.xml에서 mustache의존성 설정을 했으면 생략 가능
      suffix: #.mustache pom.xml에서 mustache의존성 설정을 했으면 생략 가능

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:         
          google:
            client-id: 459093323388-20pefg2eicfe627djg0r3nmoro7k995p.apps.googleusercontent.com
            client-secret: 5p2krk5nFkisYY7CXiMDa3w2
            scope:
            - email
            - profile